### ISSUE TITLE
Allow for more granularity in exclusions

### ISSUE THREAD

**Issue by kmcquade** [salesforce/cloudsplaining#86]
Right now, you can either AllowList or BlockList in an exclusions file - either entire principal names, entire actions, or entire policy names. However, this can have some unintended side effects. For example:

If we exclude AdministratorAccess under `policies`, this excludes AdministratorAccess from showing up **anywhere* - including if AdministratorAccess is assigned to an Ec2 instance profile (yikes).

```yaml
policies:
- "AdministratorAccess"
roles:
- ""
users:
- ""
groups:
- ""
include-actions:
  - "s3:GetObject"
exclude-actions:
- ""
```

Instead, we should allow for some granularity, where we can still exclude entire policies from the scan, but we can also specify which roles/groups/users are allowed to have those policies. For example:

```yaml
policies:
- ""
roles:
- "MyRole": AdministratorAccess
users:
- "Obama":
  - "AdministratorAccess"
  - "PlzComeBack2Us"
groups:
- ""
include-actions:
  - "s3:GetObject"
exclude-actions:
- ""
```

Also, I might want to consider making the values under each one of these top-level keys object types instead of list types. There's no need for it to be list types, I think. Then it would look like:

```yaml
policies:
    ""
roles:
    MyRole: AdministratorAccess
users:
    Obama:
        AdministratorAccess
        PlzComeBack2Us
groups:
    ""
include-actions:
    "s3:GetObject"
exclude-actions:
    ""
```
